### ISSUE TITLE
Creating an API

### ISSUE THREAD

**Issue by claudiosegala** [claudiosegala/playbook-centeias#22]
Create an API to provide history information and other informations.

- [ ] Configure API
- [ ] Create History table (with information of what action was done, search, creation, edition)
- [ ] Create API that gives History information
- [ ] Create API that gives Request information

**Comment by CrimsonCrown** [comment]
@gabrielalmeidaa any estimation on when this will be ready? Need help?

**Comment by claudiosegala** [comment]
@gabrielalmeidaa, after creating you must add a documentation to the seed explaining what APIs are given and so on.
