### ISSUE TITLE
Implement 'Request edition' funcionality

### ISSUE THREAD

**Issue by gabrielalmeidaa** [claudiosegala/playbook-centeias#6]
A common user should be able to ask for further explanations when they don't understand some process description. This action should allow the user to write a message letting the admin know what's the problem and should trigger an email to the admin.

**Comment by claudiosegala** [comment]
This enhancement can be delayed to the second release (mid-November) because it won't affect the initial user experience.

**Comment by claudiosegala** [comment]
Every user can click the button to submit a change request. The button will be in article and sub article. When clicked, go to a page of creating request where the user will submit a message and once is finished, they return to the article or sub article they where reading. This can maybe be done by a modal.
When a admin is logged. They have access to the all requests (which appear on the sidenav) in a table.
A nice implementation would be creating a table called Requests. Request would have:
bool resolved
string message
int article_id
int subarticle_id
int created_by

**Comment by claudiosegala** [comment]
Non user can see all and create requests. Users can edit. Admin can delete.

**Comment by CrimsonCrown** [comment]
@gabrielalmeidaa the part of the users abilities described above are implemented? Can I close this issue?
